configfile: "config/config.yaml"

wildcard_constraints:
    SAMPLE="M\d\d\d\d"

include: "rules/common.smk"
include: "rules/controls.smk"
include: "rules/testcases.smk"
include: "differential_methylation.smk"

rule all:
    input:
        get_one_beta_target
        #get_one_ttest_target
        #get_all_ttest_targets
        #get_all_beta_targets
