### Biplot illustration
```{r}
ggplot() + geom_point(data=all.chr.tests, aes(x=pvalue, y=effect.size), shape='.', color='darkgray') + 
geom_point(data=all.chr.tests %>% filter(pvalue<0.05), aes(x=pvalue, y=effect.size), 
size=0.25, color='black') + geom_point(data=all.chr.tests %>% filter(pvalue<0.05 & abs(effect.size)>1.5), 
aes(x=pvalue, y=effect.size),color='red', size=1) + xlab("P-value") + ylab("Effect Size") + 
geom_hline(yintercept=0, linetype='dashed', alpha=0.5) + ggrepel::geom_label_repel(data=all.chr.tests %>% 
filter(pvalue<0.05 & abs(effect.size)>1.5), aes(x=pvalue, y=effect.size, label=gene)) + 
ggtitle(testSample)
```

```{r}
filter.set <- all.chr.tests %>% filter(pvalue < 0.01) %>% filter(abs(effect.size) > 1.5) %>% arrange(desc(effect.size))
filter.set
outputdir <- paste("results/",snakemake@wildcards[["SAMPLE"]],"_meow_results/", sep="")
write.csv(filter.set, paste(outputdir,testSample,"_significant_DMR_",snakemake@wildcards[["TEST"]],".csv", sep=""), row.names=FALSE)
write.csv(all.chr.tests, paste(outputdir,testSample,"_all_DMR_",snakemake@wildcards[["TEST"]],".csv", sep=""), row.names=FALSE)
ggsave(paste(outputdir,testSample,"_significant_DMR_",snakemake@wildcards[["TEST"]],".png", sep=""), width=6, height=4, unit="in", dpi=300)
```

## DMR Plots

```{r}
cpgnames <- filter.set %>% pull(cpg)

plotRibbonGenes(cpg.select.df,cpgs=cpgnames,testSample,exclusions=setdiff(row.names(tmdf),testSample), minmax=FALSE) + ggtitle(testSample)
ggsave(paste(outputdir,testSample,"_significant_DMR_",snakemake@wildcards[["TEST"]],".png", sep=""), dpi=300, height=11, width=8, unit="in")

cpgBoxPlots(cpg.select.df, testSample,exclusions=setdiff(row.names(tmdf),testSample),cpgs=cpgnames)
ggsave(paste(outputdir,testSample,"_significant_DMR_",snakemake@wildcards[["TEST"]],".png", sep=""), dpi=300, height=11, width=8, unit="in")
```